version: '3.9'
services:
  backend:
    build:
      context: ../backend
      dockerfile: docker/Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ../backend/.env.example
    depends_on:
      - db
  frontend:
    build:
      context: ../frontend
      dockerfile: docker/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ../frontend/.env.example
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
